/*
 * Isotope database for OpenShieldHIT
 * Autogenerated by "./tools/make_part_db.py"
 * 2026-03-02 15:14:40.862065
 * on host baslup.ks.se by user bassler.
 *
 * Please do not edit this file.
 */

#ifndef OSH_ISOTOPE_DB_GENERATED_H
#define OSH_ISOTOPE_DB_GENERATED_H

struct isotope {
  double amass;   /* atomic mass in amu */
  double abund;   /* relative abundance by number */
  unsigned int z; /* particle charge */
  unsigned int a; /* nucleon number */
  char symb[4];   /* chemical symbol */
};

#define OSH_ISOTOPE_DB_NISO 3353  /* number of isotopes in database */
#define OSH_ISOTOPE_DB_NELEM 119  /* number of elements in database */
#define OSH_ISOTPOPE_DB_ERR 0xFFFF /* error code */

extern const struct isotope osh_isotope_db[];
#endif /* !OSH_ISOTOPE_DB_GENERATED_H */
