#ifndef OSH_KINEMATICS_H
#define OSH_KINEMATICS_H

/**
 * @file osh_kinematics.h
 *
 * @brief Generic relativistic kinematics and direction-rotation utilities.
 *
 * @details
 * All functions are trig-free in the hot path: angles are represented by
 * their cosines and sines computed via sqrt, never via acos/atan/sin/cos.
 * The azimuthal direction is generated by disk rejection (Knuth, TAOCP Vol. 2,
 * §3.4.1) rather than by sampling a uniform angle and calling sin/cos.
 *
 * These utilities are shared by all nuclear interaction modules (pp elastic,
 * future np / heavier-ion reactions).  Do not duplicate them in module-local
 * files.
 */

struct osh_rng;

/**
 * @brief Rotate unit direction @p v by a deflection and azimuthal direction,
 *        yielding exit direction @p w.
 *
 * @details
 * The deflection is specified by its cosine and sine (caller computes
 * sin_theta = sqrt(1 - cos_theta²) from the sampled cosine).
 * The azimuthal direction @p a, @p b = (cos φ, sin φ) is obtained without
 * trigonometry — see osh_kinematics_azimuth().
 *
 * A stable orthonormal transverse basis {u1, u2} is built via
 * osh_vect_orthogonal_basis_norm().  The rotation is:
 *   w_raw = cos_theta·v + sin_theta·(a·u1 + b·u2)
 * followed by renormalisation to guard against floating-point drift.
 *
 * For sin_theta < 1e-9 the function simply copies @p v to @p w.
 *
 * @param[in]  v          Incident unit direction (length 3).
 * @param[out] w          Exit unit direction (length 3); may alias @p v.
 * @param[in]  cos_theta  Cosine of deflection angle.
 * @param[in]  sin_theta  Sine of deflection angle (must be >= 0).
 * @param[in]  a          cos φ component of azimuthal unit vector.
 * @param[in]  b          sin φ component of azimuthal unit vector.
 */
void osh_kinematics_rotate_dir_cos(
    double const v[3], double w[3], double cos_theta, double sin_theta, double a, double b);

/**
 * @brief Generate an azimuthal unit vector (cos φ, sin φ) without trig.
 *
 * @details
 * Algorithm (Knuth, TAOCP Vol. 2, §3.4.1 — Weierstrass substitution form):
 *   1. Q = 2·U₁ − 1  (U₁ ∈ [0,1) → Q ∈ [-1,1))
 *   2. R = U₂         (U₂ ∈ [0,1) — upper half of unit square)
 *   3. QR = Q²+R²;  retry if QR > 1 or QR == 0  (avg ~1.27 deviates)
 *   4. cos φ = (Q²−R²)/QR,   sin φ = 2·Q·R/QR
 *
 * No sqrt, no trig.  The recoil particle's azimuthal direction is simply
 * (-cos φ, -sin φ) — no extra sample needed.
 *
 * @param[in,out] rng      RNG state (consumes ~1.27 uniform deviates on average).
 * @param[out]    cos_phi  cos φ ∈ [-1, 1].
 * @param[out]    sin_phi  sin φ ∈ [-1, 1].
 */
void osh_kinematics_azimuth(struct osh_rng *rng, double *cos_phi, double *sin_phi);

/**
 * @brief Full-relativistic 2-body elastic kinematics for equal-mass particles.
 *
 * @details
 * GLOREN algorithm: Lorentz boost of the CM 4-momenta back to the lab frame.
 * No trigonometric functions are used; sin(θ_CM) is derived from sqrt(1−cos²).
 *
 * The incident particle moves along the positive z-axis in the lab.  The
 * scatter and recoil directions relative to z are returned as cosines.
 * The caller applies the global rotation (using osh_kinematics_rotate_dir_cos)
 * to obtain Cartesian directions in the world frame.
 *
 * Valid for all lab kinetic energies T > 0.  Handles the non-relativistic
 * limit correctly: at low T, cos_theta1 + cos_theta2 → 0 (θ₁ + θ₂ → π/2).
 *
 * Energy conservation: *e1_lab_mev + *e2_lab_mev == T_lab up to floating-point
 * rounding (exact within ~1 ULP for typical proton energies 10–5000 MeV).
 *
 * @param[in]  T_lab          Incident particle lab kinetic energy [MeV].
 * @param[in]  mp             Common rest mass of both particles [MeV/c²].
 * @param[in]  cos_theta_cm   CM scattering angle cosine (from CDF; no arccos).
 * @param[out] cos_theta1_lab Lab-frame scatter angle cosine (incident particle).
 * @param[out] e1_lab_mev     Scattered particle lab kinetic energy [MeV].
 * @param[out] cos_theta2_lab Lab-frame recoil angle cosine (target particle, >= 0).
 * @param[out] e2_lab_mev     Recoil particle lab kinetic energy [MeV].
 */
void osh_kinematics_elastic_equal_mass_lab(double T_lab,
                                           double mp,
                                           double cos_theta_cm,
                                           double *cos_theta1_lab,
                                           double *e1_lab_mev,
                                           double *cos_theta2_lab,
                                           double *e2_lab_mev);

#endif /* OSH_KINEMATICS_H */
