"""Fit the 1-D inverse-CDF coefficients for the universal Landau variable
(κ < 0.01 regime) and emit the C coefficient header + a golden fixture.

The Landau λ is universal (no κ, β dependence — those enter only via ξ and λ̄).
Reference: the standard (DENLAN/CERNLIB) Landau, obtained from scipy.stats.landau
(BSD) via the exact affine map to the physics convention,
    λ_DENLAN = (π/2)·λ_scipy + b ,   b fixed by the DENLAN mode −0.22278,
the κ→0 limit of the exact Vavilov λ.  The fit follows an approach by Bjarne
Thomsen (Aarhus University, Aarhus, Denmark, 2012); the coefficients are
OpenShieldHIT-specific, regenerated from the distribution.

Runtime form (pole-free polynomial, same idea as the Vavilov sampler): branch by
u; per branch λ = Σ_k a_k · xn^k, xn a normalised transform of u.
"""

import os
import numpy as np
from scipy.stats import landau

HERE = os.path.dirname(__file__)
HDR = os.path.join(HERE, "..", "..", "src", "physics", "atomic",
                   "osh_physics_straggling_landau_coeffs.h")
FIX = os.path.join(HERE, "..", "..", "tests", "fixtures", "vavilov", "landau_ppf.csv")

A = np.pi / 2.0
B = -0.22278 - A * float(np.asarray(
    __import__("scipy.optimize", fromlist=["minimize_scalar"]).minimize_scalar(
        lambda x: -landau.pdf(x), bounds=(-1, 0), method="bounded",
        options={"xatol": 1e-10}).x))

UMIN, UMAX = 1e-3, 0.995
KIND = {"nlog": 0, "u": 1, "nlog1mu": 2}
# (u_hi, transform, degree)
BANDS = [(0.05, "nlog", 5), (0.60, "u", 5), (0.95, "nlog1mu", 5), (UMAX + 1e-4, "nlog1mu", 6)]
MAXP = max(d for _, _, d in BANDS) + 1


def ppf(u):
    return A * landau.ppf(u) + B


def xform(u, kind):
    return {"nlog": -np.log(u), "u": u, "nlog1mu": -np.log1p(-u)}[kind]


def fit_band(u_lo, u_hi, kind, deg):
    u = np.linspace(u_lo, u_hi, 400)
    x = xform(u, kind)
    xm, xh = 0.5 * (x.min() + x.max()), 0.5 * (x.max() - x.min())
    xn = (x - xm) / xh
    coef = np.polyfit(xn, ppf(u), deg)[::-1]  # ascending powers
    uv = np.linspace(u_lo, u_hi, 1500)
    xv = (xform(uv, kind) - xm) / xh
    md = float(np.max(np.abs(np.polyval(coef[::-1], xv) - ppf(uv))))
    return coef, xm, xh, md


def fmt(x):
    return f"{x:+.10e}"


def main():
    lo = UMIN
    coefs = np.zeros((len(BANDS), MAXP))
    xmid = np.zeros(len(BANDS)); xhalf = np.zeros(len(BANDS))
    worst = 0.0
    for i, (uhi, kind, deg) in enumerate(BANDS):
        c, xm, xh, md = fit_band(lo, uhi, kind, deg)
        coefs[i, :deg + 1] = c
        xmid[i], xhalf[i] = xm, xh
        worst = max(worst, md)
        lo = uhi
    print(f"Landau fit worst maxdev(lambda) = {worst:.3e}")

    with open(HDR, "w") as f:
        f.write("/* GENERATED by tools/vavilov_fit/emit_landau.py — DO NOT EDIT.\n")
        f.write(" * Reproducible 1-D fit of the universal (DENLAN) Landau inverse CDF,\n")
        f.write(" * regenerated from the distribution by the tools/vavilov_fit scripts.\n")
        f.write(" * Based on an approach by Bjarne Thomsen, Dept. of Physics and Astronomy,\n")
        f.write(" * Aarhus University, Aarhus, Denmark (2012).  The coefficients are\n")
        f.write(" * OpenShieldHIT-specific, regenerated from the distribution by these scripts.\n")
        f.write(f" * Worst |lambda_fit - lambda_ref|: {worst:.2e}. */\n")
        f.write("#ifndef OSH_PHYSICS_STRAGGLING_LANDAU_COEFFS_H\n")
        f.write("#define OSH_PHYSICS_STRAGGLING_LANDAU_COEFFS_H\n\n")
        f.write(f"#define OSH_LAN_NB {len(BANDS)}\n#define OSH_LAN_MAXP {MAXP}\n")
        f.write(f"#define OSH_LAN_UMIN {UMIN:.10e}\n#define OSH_LAN_UMAX {UMAX:.6f}\n\n")
        f.write("static const double osh_lan_uhi[] = {%s};\n" %
                ", ".join(fmt(h) for h, _, _ in BANDS))
        f.write("static const int osh_lan_kind[] = {%s};\n" %
                ", ".join(str(KIND[k]) for _, k, _ in BANDS))
        f.write("static const int osh_lan_deg[] = {%s};\n" %
                ", ".join(str(d) for _, _, d in BANDS))
        f.write("static const double osh_lan_xmid[] = {%s};\n" % ", ".join(fmt(v) for v in xmid))
        f.write("static const double osh_lan_xhalf[] = {%s};\n" % ", ".join(fmt(v) for v in xhalf))
        flat = coefs.reshape(-1)
        f.write(f"static const double osh_lan_coef[{flat.size}] = {{\n")
        for i in range(0, flat.size, 6):
            f.write("  " + ", ".join(fmt(v) for v in flat[i:i + 6]) + ",\n")
        f.write("};\n\n#endif /* OSH_PHYSICS_STRAGGLING_LANDAU_COEFFS_H */\n")
    print("wrote", os.path.normpath(HDR))

    with open(FIX, "w") as f:
        f.write("# Universal Landau (DENLAN) inverse CDF lambda(u); OpenShieldHIT reference.\n")
        f.write("# lambda_denlan = (pi/2)*scipy.stats.landau.ppf(u) + b.  columns: u lambda\n")
        for u in np.concatenate([np.geomspace(1e-3, 0.05, 12),
                                 np.linspace(0.06, 0.94, 30),
                                 1 - np.geomspace(5e-3, 0.05, 10)[::-1]]):
            f.write(f"{u:.6e} {ppf(u):.9e}\n")
    print("wrote", os.path.normpath(FIX))


if __name__ == "__main__":
    main()
