"""Fit all Vavilov regions and emit the committed C coefficient header.

Runtime form (pole-free polynomial special case of the vavinv rational, Q=1):
per (κ-band × u-band) region,
    λ(u; κ, β²) = Σ_{k=0..mdeg} a_k(κ,β) · xn^k ,
    a_k(κ,β)   = Σ_{i<NKA, j<NBE} c[k][i,j] · T_i(κ̂) T_j(β̂) ,
where κ̂ = normalised ln κ (band [klo,khi]), β̂ = normalised β² ([blo,bhi]),
xn = (x'(u) − xmid)/xhalf, x'(u) the per-u-band transform.  The fit follows an
approach by Bjarne Thomsen (Aarhus University, Aarhus, Denmark, 2012); the
coefficients are OpenShieldHIT-specific, regenerated from the exact Vavilov
reference.
"""

import os
import numpy as np
from fit_vavilov import fit_region, kbands_by_index, NKA, NBE, NT

HERE = os.path.dirname(__file__)
HDR = os.path.join(HERE, "..", "..", "src", "physics", "atomic",
                   "osh_physics_strag_vavilov_coeffs.h")

BLO, BHI = 0.05, 0.99
NKB = 3  # wide κ-bands: many nodes per band vs NKA=4 keeps the κ-fit
         # over-determined (avoids between-node oscillation in the small-κ tail)
KIND_ID = {"nlog": 0, "u": 1, "nlog1mu": 2}
UBANDS = [(0.05, "nlog", 6), (0.60, "u", 5), (0.95, "nlog1mu", 6), (0.9951, "nlog1mu", 6)]
MAXP = max(m for _, _, m in UBANDS) + 1  # padded power count


def fmt(x):
    return f"{x:+.10e}"


def main():
    cache = np.load(os.path.join(HERE, "ref_cache.npz"))
    K, U = cache["kappa"], cache["u"]
    kbands = kbands_by_index(K.size, NKB, overlap=0)

    # dispatch boundaries: geometric midpoint between adjacent bands' edge nodes
    kdisp_hi, klo, khi = [], [], []
    for b, ki in enumerate(kbands):
        klo.append(float(K[ki[0]])); khi.append(float(K[ki[-1]]))
        if b < NKB - 1:
            kdisp_hi.append(float(np.sqrt(K[kbands[b][-1]] * K[kbands[b + 1][0]])))
    kdisp_hi.append(1.0e30)  # last band catches up to κ=10

    ulo = U.min()
    coef = np.zeros((NKB, len(UBANDS), MAXP, NT))
    umid = np.zeros(len(UBANDS)); uhalf = np.zeros(len(UBANDS))
    worst = 0.0
    for b, ki in enumerate(kbands):
        lo = ulo
        for ub, (uhi, kind, mdeg) in enumerate(UBANDS):
            ac, _, md, xm, xh = fit_region(cache, lo, uhi, kind, ki, BLO, BHI, mdeg, 0)
            coef[b, ub, :mdeg + 1, :] = ac
            umid[ub], uhalf[ub] = xm, xh
            worst = max(worst, md)
            lo = uhi
    print(f"worst maxdev(lambda) at fit nodes = {worst:.3e}")

    ukind = [KIND_ID[k] for _, k, _ in UBANDS]
    udeg = [m for _, _, m in UBANDS]
    uhi = [h for h, _, _ in UBANDS]

    # Independent validation on the fixture grid (κ, β² nodes disjoint from the
    # cache) — this catches between-node oscillation that node-only checks miss.
    def _xf(u, k):
        return -np.log(u) if k == 0 else (u if k == 1 else -np.log1p(-u))

    def _eval(ka, be, uu):
        uu = min(max(uu, ulo), 0.995)
        bb = 0
        while bb < NKB - 1 and ka >= kdisp_hi[bb]:
            bb += 1
        kn = (2 * np.log(ka) - np.log(klo[bb]) - np.log(khi[bb])) / (np.log(khi[bb]) - np.log(klo[bb]))
        vb = 0
        while vb < len(UBANDS) - 1 and uu > uhi[vb]:
            vb += 1
        xn = (_xf(uu, ukind[vb]) - umid[vb]) / uhalf[vb]
        bn = (2 * be - BLO - BHI) / (BHI - BLO)
        tk = [1, kn, 2 * kn * kn - 1, (4 * kn * kn - 3) * kn]
        tb = [1, bn, 2 * bn * bn - 1]
        t = [tk[i] * tb[j] for i in range(NKA) for j in range(NBE)]
        lam = 0.0
        for k in range(udeg[vb], -1, -1):
            lam = lam * xn + sum(t[i] * coef[bb, vb, k, i] for i in range(NT))
        return lam

    fx = os.path.join(HERE, "..", "..", "tests", "fixtures", "vavilov", "vavilov_ppf.csv")
    fdev = 0.0
    if os.path.exists(fx):
        with open(fx) as fh:
            for ln in fh:
                if ln.startswith("#") or not ln.strip():
                    continue
                ka, be, uu, lr = map(float, ln.split())
                fdev = max(fdev, abs(_eval(ka, be, uu) - lr))
    worst = max(worst, fdev)
    print(f"worst maxdev(lambda) on independent fixture grid = {fdev:.3e}")

    with open(HDR, "w") as f:
        f.write("/* GENERATED by tools/vavilov_fit/emit_coeffs.py — DO NOT EDIT.\n")
        f.write(" * Reproducible polynomial+Chebyshev fit of the exact Vavilov distribution\n")
        f.write(" * (Vavilov 1957), regenerated from the distribution by the tools/vavilov_fit\n")
        f.write(" * scripts.  Based on an approach by Bjarne Thomsen, Dept. of Physics and\n")
        f.write(" * Astronomy, Aarhus University, Aarhus, Denmark (2012).  The coefficients are\n")
        f.write(" * OpenShieldHIT-specific, regenerated from the distribution by these scripts.\n")
        f.write(f" * Worst |lambda_fit - lambda_exact| over all regions: {worst:.2e}. */\n")
        f.write("#ifndef OSH_PHYSICS_STRAG_VAVILOV_COEFFS_H\n")
        f.write("#define OSH_PHYSICS_STRAG_VAVILOV_COEFFS_H\n\n")
        f.write(f"#define OSH_VAV_NKA {NKA}\n#define OSH_VAV_NBE {NBE}\n")
        f.write(f"#define OSH_VAV_NT {NT}\n#define OSH_VAV_NKB {NKB}\n")
        f.write(f"#define OSH_VAV_NUB {len(UBANDS)}\n#define OSH_VAV_MAXP {MAXP}\n\n")
        f.write(f"/* xform id: 0=-log(u) 1=u 2=-log(1-u) ; beta2 norm range */\n")
        f.write(f"#define OSH_VAV_BLO {BLO:.6f}\n#define OSH_VAV_BHI {BHI:.6f}\n")
        f.write(f"#define OSH_VAV_UMIN {ulo:.10e}\n#define OSH_VAV_UMAX 0.995\n\n")

        def arr(name, vals, typ="double", fmtf=fmt):
            f.write(f"static {typ} const {name}[] = {{{', '.join(fmtf(v) for v in vals)}}};\n")

        arr("osh_vav_kdisp_hi", kdisp_hi)
        arr("osh_vav_klo", klo)
        arr("osh_vav_khi", khi)
        arr("osh_vav_uhi", uhi)
        arr("osh_vav_ukind", ukind, "int", lambda v: str(int(v)))
        arr("osh_vav_udeg", udeg, "int", lambda v: str(int(v)))
        arr("osh_vav_umid", umid)
        arr("osh_vav_uhalf", uhalf)
        f.write("\n/* coef[kband][uband][power][cheb_term], flat row-major */\n")
        flat = coef.reshape(-1)
        f.write(f"static double const osh_vav_coef[{flat.size}] = {{\n")
        for i in range(0, flat.size, 6):
            f.write("    " + ", ".join(fmt(v) for v in flat[i:i + 6]) + ",\n")
        f.write("};\n\n#endif /* OSH_PHYSICS_STRAG_VAVILOV_COEFFS_H */\n")
    print("wrote", os.path.normpath(HDR))


if __name__ == "__main__":
    main()
