"""Generate the committed golden inverse-CDF fixtures for the straggling
samplers.  Offline: run once, commit the CSVs under tests/fixtures/vavilov/.

Values are computed from the exact Vavilov distribution (vavilov_exact.py, from
the published 1957 definition) and are OpenShieldHIT-specific, reproducible from
these scripts.  The runtime C evaluators are validated against these tables.
"""

import os
import numpy as np

from vavilov_exact import ppf

OUT = os.path.join(os.path.dirname(__file__), "..", "..", "tests", "fixtures", "vavilov")

# Vavilov regime κ ∈ [0.01, 10]; vavinv's valid random range is u ≤ ~0.995, so
# the fixture stops at 0.995 (the far tail is out of the sampler's range and
# κ < 0.01 is handled by the Landau sampler).
KAPPA = np.geomspace(0.01, 10.0, 16)
BETA2 = np.array([0.05, 0.30, 0.55, 0.80, 0.99])
U = np.concatenate([
    np.array([1e-3, 3e-3, 0.01, 0.03]),
    np.linspace(0.05, 0.95, 19),
    np.array([0.97, 0.99, 0.995]),
])


def main():
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, "vavilov_ppf.csv")
    with open(path, "w") as fh:
        fh.write("# Exact Vavilov inverse CDF lambda(u; kappa, beta2).\n")
        fh.write("# From the Vavilov (1957) distribution; generated by tools/vavilov_fit.\n")
        fh.write("# columns: kappa beta2 u lambda\n")
        for kappa in KAPPA:
            for beta2 in BETA2:
                lam = ppf(U, float(kappa), float(beta2), n=500)
                for u, l in zip(U, lam):
                    fh.write(f"{kappa:.6e} {beta2:.6e} {u:.6e} {l:.9e}\n")
        print(f"wrote {path}: {len(KAPPA) * len(BETA2) * len(U)} rows "
              f"({len(KAPPA)} kappa x {len(BETA2)} beta2 x {len(U)} u)")


if __name__ == "__main__":
    main()
