/*
 * Particle and isotope database for OpenShieldHIT
 * Autogenerated by "make_part_db.py"
 * 2025-07-25 18:36:17.162875
 * on host altair by user bassler.
 *
 * Please do not edit this file.
 */
#ifndef _SH_PARTDB
#define _SH_PARTDB

struct isotope {
  double amass;   /* atomic mass in amu */
  double abund;   /* relative abundance */
  unsigned int z; /* particle charge */
  unsigned int a; /* nucleon number */
  char symb[4];   /* chemical symbol */
};

#define _OSH_ISODB_NISO 3353  /* number of isotopes in database */
#define _OSH_ISODB_NELEM 119  /* number of elements in database */
#define _OSH_ISODB_ERR 0xFFFF /* error code */

extern const struct isotope _isotopes[];
extern const unsigned int _isotopes_len[];
extern const unsigned int _isotopes_idx[];
extern const unsigned int _isotopes_idx_default[];
extern const double _jpart_amass[];
extern const unsigned int _jpart_nucleons[];
extern const int _jpart_charge[];
 
#endif /* !_SH_PARTDB */
