#ifndef OSH_PARTICLE_H
#define OSH_PARTICLE_H

#include "_osh_partdb.h" /* autogenerated DB */


/* list of particle IDs. */
/* These are inspired by JPART found in osh_jpart.h , but they are not identical */
/* Negative numbers for scoring only, as they represent groups */
#define OSH_PARTG_HADRON     -4  /* all (anti-)hadrons */
#define OSH_PARTG_UNCHARGED  -3  /* all uncharged particles */
#define OSH_PARTG_CHARGED    -2  /* all charged particles */
#define OSH_PARTG_ALL        -1  /* all particles */

#define OSH_PART_ZERO        0  /* zero-physics virtual particle for testing */
#define OSH_PART_HADRON      1  /* hadrons (protons, neutrons, ions) */
#define OSH_PART_AHADRON     2  /* anti-hadrons (antiprotons, anti-neutrons...) */
#define OSH_PART_PIMINUS     3  /* pi- */
#define OSH_PART_PIPLUS      4  /* pi+ */
#define OSH_PART_PIZERO      5  /* pi0 */
#define OSH_PART_KMINUS      8  /* K- */
#define OSH_PART_KPLUS       9  /* K+ */

#define OSH_PART_KZERO      10  /* K0 */
#define OSH_PART_KTLD       11 /* K~ */     // TODO check what this is
#define OSH_PART_GAMMA      12  /* Gamma ray */
#define OSH_PART_ELECTRON   13  /* Electron */
#define OSH_PART_POSITRON   14  /* Position */
#define OSH_PART_MUMINUS    15  /* Muon mu- */
#define OSH_PART_MUPLUS     16  /* Muon mu+ */
#define OSH_PART_ENU        17  /* e-neutrino  */
#define OSH_PART_EANU       18  /* e-antineutrino  */
#define OSH_PART_MUNU       19  /* mu-neutrino */
#define OSH_PART_MUANU      20  /* mu-antineutrino */

#define OSH_PART_INVALID    32768 /* used for returning invalid IDs. Positive, so it can be used signed and unsigned. */

#define OSH_JPART_ALL           -1
#define OSH_JPART_FRAG           0  /* heavy ion fragment ID used by GENTRE */
#define OSH_JPART_NEUTRON        1
#define OSH_JPART_PROTON         2
#define OSH_JPART_PIMINUS        3
#define OSH_JPART_PIPLUS         4

#define OSH_JPART_PIZERO         5
#define OSH_JPART_ANTINEUTRON    6
#define OSH_JPART_ANTIPROTON     7
#define OSH_JPART_KMINUS         8
#define OSH_JPART_KPLUS          9

#define OSH_JPART_KZERO         10
#define OSH_JPART_KTLD          11
#define OSH_JPART_GAMMA         12
#define OSH_JPART_ELECTRON      13
#define OSH_JPART_POSITRON      14

#define OSH_JPART_MUMINUS       15
#define OSH_JPART_MUPLUS        16
#define OSH_JPART_ENU           17
#define OSH_JPART_EANU          18
#define OSH_JPART_MUNU          19

#define OSH_JPART_MUANU         20
#define OSH_JPART_DEUTERON      21
#define OSH_JPART_TRITON        22
#define OSH_JPART_HE3           23
#define OSH_JPART_HE4           24

#define OSH_JPART_HEAVYION      25
#define OSH_JPART_INVALID    32768

struct particle {
    double amass;       /* particle mass in MeV/c**2 */
    double amu;         /* particle mass in amu */
    double weight;      /* statistical weight (1.0 is normal weight) */
    signed int id;      /* particle id (SH_PART_ZERO, OSH_PART_HADRON or similar...) */
    signed int z;       /* charge (hadrons: number of protons in nucleus). E.g. pions may have negative charge. */
    unsigned int a;     /* nucleon number ( > 0 only for hadrons) */
    unsigned int gen;   /* generation, 0 for primary particles, 1 for 1st generation etc... */
    unsigned int nprim; /* originated from this primary particle number (NCUR in shield.f) */
    int pdg;            /* particle PDG code */
};

void osh_particle_print(struct particle part);

#endif  /* OSH_PARTICLE_H */