add_library(osh_scoring
    osh_scoring.c
    runtime/osh_scoring_accumulator.c
    runtime/osh_scoring_compile.c
    runtime/osh_scoring_filter_runtime.c
    runtime/osh_scoring_postprocess.c
    runtime/osh_scoring_shadow.c
    runtime/osh_scoring_snapshot.c
    runtime/osh_scoring_step.c
    runtime/osh_scoring_point.c
    save/osh_scoring_save.c
    save/osh_scoring_sink.c
    save/osh_scoring_save_ascii.c
    save/osh_scoring_save_bdo2019_raw.c
    save/osh_scoring_save_bdo2019.c
    save/osh_scoring_save_rtdose.c
)

target_include_directories(osh_scoring
    PUBLIC
        ${PROJECT_SOURCE_DIR}/src
        ${PROJECT_SOURCE_DIR}/include
)

target_link_libraries(osh_scoring
    PUBLIC
        osh_common
        osh_dicom
        osh_raytrace
)
