#ifndef _OSH_GEMCA2_VOXEL_DEFINES
#define _OSH_GEMCA2_VOXEL_DEFINES

#define OSH_GEMCA_VOXEL_LITTLEENDIAN 0
#define OSH_GEMCA_VOXEL_BIGENDIAN 1

#define OSH_GEMCA_VOXEL_INTEGER 0
#define OSH_GEMCA_VOXEL_FLOAT 1

#define OSH_GEMCA_VOXEL_SUFFIX_HED ".hed"
#define OSH_GEMCA_VOXEL_SUFFIX_CTX ".ctx"

#define OSH_GEMCA_VOXEL_HU2WEPL_ALG1 1
#define OSH_GEMCA_VOXEL_HU2WEPL_ALG2 2
#define OSH_GEMCA_VOXEL_HU2WEPL_ALG3 3

#endif /* _OSH_GEMCA2_VOXEL_DEFINES */
