#!/usr/bin/env python3
"""
tools/condense_pa_xsec.py

Condense the committed p+A nonelastic reference curves (issue #277) into a C
data header for the transport's reaction-cross-section lookup.

Reads the `endfb8-nonel` blocks (ENDF/B-VIII.0 proton sublibrary, LA150h
lineage — the evaluation behind the ICRU 63 nonelastic tables) from
tests/reference/xsec/p_*.txt (produced by tools/fetch_pa_xsec.py) and
resamples them lin-lin onto a uniform 1-MeV grid:

  * below the evaluation's first point: 0 (channel closed);
  * above the evaluation's last point (150 MeV): flat clamp — supported by
    the Renberg 1972 measurements (p+O 296 mb at 230 MeV vs the 295 mb
    clamp).

Output: src/physics/nuclear/osh_nuclear_sigma_reac_data.h

Usage:
    python tools/condense_pa_xsec.py
"""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path

E_MIN_MEV = 1.0
E_STEP_MEV = 1.0
N_POINTS = 250  # 1..250 MeV

TARGETS = (
    ("o16", 8, 16, "p_O16.txt"),
    ("c12", 6, 12, "p_C12.txt"),
)

SOURCE_BLOCK = "endfb8-nonel"


def read_block(path: Path, block: str) -> list[tuple[float, float]]:
    pairs = []
    with open(path) as fh:
        for line in fh:
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            parts = s.split()
            if parts[0] == block:
                pairs.append((float(parts[1]), float(parts[2])))
    if not pairs:
        raise ValueError(f"{path}: no '{block}' rows")
    return sorted(pairs)


def resample(pairs: list[tuple[float, float]]) -> list[float]:
    es = [p[0] for p in pairs]
    ss = [p[1] for p in pairs]
    out = []
    for i in range(N_POINTS):
        e = E_MIN_MEV + i * E_STEP_MEV
        if e < es[0]:
            out.append(0.0)
        elif e >= es[-1]:
            out.append(ss[-1])
        else:
            j = 0
            while es[j + 1] < e:
                j += 1
            f = (e - es[j]) / (es[j + 1] - es[j])
            out.append(ss[j] + f * (ss[j + 1] - ss[j]))
    return out


def c_array(name: str, values: list[float]) -> str:
    body = []
    for i in range(0, len(values), 7):
        body.append("    " + ", ".join(f"{v:.6e}f" for v in values[i : i + 7]) + ",")
    joined = "\n".join(body).rstrip(",")
    return f"static float const {name}[OSH_NUCLEAR_SIGMA_REAC_NPOINTS] = {{\n{joined}}};\n"


def main() -> None:
    root = Path(__file__).resolve().parent.parent
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--xsec-dir", type=Path, default=root / "tests" / "reference" / "xsec")
    ap.add_argument("--out", type=Path, default=root / "src" / "physics" / "nuclear" / "osh_nuclear_sigma_reac_data.h")
    args = ap.parse_args()

    chunks = []
    chunks.append("/* Auto-generated by tools/condense_pa_xsec.py — do not edit.\n")
    chunks.append(" * Source  : ENDF/B-VIII.0 proton sublibrary MF3/MT5 (LA150h lineage; the\n")
    chunks.append(" *           evaluation behind the ICRU 63 nonelastic tables), condensed\n")
    chunks.append(" *           from tests/reference/xsec/ (issue #277).\n")
    chunks.append(" * Grid    : uniform, E = 1..250 MeV, 1 MeV steps, lin-lin resampled.\n")
    chunks.append(" *           Below the evaluation's threshold: 0.  Above its last point\n")
    chunks.append(" *           (150 MeV): flat clamp, supported by Renberg 1972 (p+O 296 mb\n")
    chunks.append(" *           at 230 MeV vs the 295 mb clamp).\n")
    chunks.append(" * Units   : energy [MeV], cross section [mb].\n")
    chunks.append(f" * Generated: {datetime.now().strftime('%Y-%m-%d %H:%M %Z').strip()}\n")
    chunks.append(" */\n\n")
    chunks.append("#ifndef OSH_NUCLEAR_SIGMA_REAC_DATA_H\n#define OSH_NUCLEAR_SIGMA_REAC_DATA_H\n\n")
    chunks.append(f"#define OSH_NUCLEAR_SIGMA_REAC_E_MIN_MEV {E_MIN_MEV}\n")
    chunks.append(f"#define OSH_NUCLEAR_SIGMA_REAC_E_STEP_MEV {E_STEP_MEV}\n")
    chunks.append(f"#define OSH_NUCLEAR_SIGMA_REAC_NPOINTS {N_POINTS}\n\n")

    entries = []
    for tag, z, a, fname in TARGETS:
        sigma = resample(read_block(args.xsec_dir / fname, SOURCE_BLOCK))
        chunks.append(f"/* p + {tag.upper()}: Z={z} A={a} */\n")
        chunks.append(c_array(f"osh_nuclear_sigma_reac_{tag}_mb", sigma))
        chunks.append("\n")
        entries.append((tag, z, a))

    chunks.append("struct osh_nuclear_sigma_reac_table {\n")
    chunks.append("    unsigned int z;\n")
    chunks.append("    unsigned int a;\n")
    chunks.append("    float const *sigma_mb;\n")
    chunks.append("};\n\n")
    chunks.append("static struct osh_nuclear_sigma_reac_table const osh_nuclear_sigma_reac_tables[] = {\n")
    for tag, z, a in entries:
        chunks.append(f"    {{{z}u, {a}u, osh_nuclear_sigma_reac_{tag}_mb}},\n")
    chunks.append("};\n\n")
    chunks.append("#endif /* OSH_NUCLEAR_SIGMA_REAC_DATA_H */\n")

    args.out.write_text("".join(chunks))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
