import sys
import logging
import socket
import getpass
from datetime import datetime
from urllib import request, error

ISO_URL = "https://physics.nist.gov/cgi-bin/Compositions/stand_alone.pl?ele=&ascii=ascii&isotype=all"
BASENAME = "osh_isotope_db_generated"
OSH_ISOTOPE_DB_ERR = 0xFFFF

logger = logging.getLogger(__name__)


def init_db(url: str = ISO_URL):
    headers = {
        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                      "(KHTML, like Gecko) Chrome/122.0 Safari/537.36",
        "Accept": "text/plain,text/html;q=0.9,*/*;q=0.8",
    }
    req = request.Request(url, headers=headers)

    try:
        with request.urlopen(req, timeout=30) as resp:
            lines = resp.read().splitlines(True)
    except error.HTTPError as e:
        raise RuntimeError(f"NIST returned HTTP {e.code} {e.reason} for {url}") from e
    except (error.URLError, TimeoutError) as e:
        raise RuntimeError(f"Failed to download isotope table from NIST: {e}") from e

    eldb = [{}]  # synthetic placeholder
    count = 0

    in_table = False
    current_z = None
    current_el_symb = None
    current = None

    for line in lines:
        # Wait for table header separator
        if b"_____" in line:
            in_table = True
            continue
        if not in_table:
            continue

        # Stop on any HTML tag once we are in the table block
        if line.lstrip().startswith(b"<"):
            break

        # Fixed-width columns from NIST ASCII table
        z_s = line[0:3].strip().decode("utf-8", "strict")
        symb_s = line[4:7].strip().decode("utf-8", "strict")
        a_s = line[8:12].strip().decode("utf-8", "strict")
        amass_s = line[13:31].strip().decode("utf-8", "strict").split("(")[0]
        abund_s = line[32:43].strip().decode("utf-8", "strict").split("(")[0]

        # Blank lines / non-data lines inside <pre>
        if not a_s or not amass_s:
            continue

        # New element begins when Z is present
        if z_s:
            logger.info(f"parsing {z_s}")
            z = int(z_s)

            # Commit previous element dict into its Z slot
            if current is not None and current_z is not None:
                while len(eldb) <= current_z:
                    eldb.append({})
                eldb[current_z] = current

            # Ensure eldb is long enough for this new Z
            while len(eldb) <= z:
                eldb.append({})

            current_z = z
            current = {}
            current_el_symb = symb_s or (current_el_symb or "")
            # The element's base symbol is the symbol on the Z line (e.g. "H", "He", "Li")
            if symb_s:
                current_el_symb = symb_s
            else:
                # Very unlikely, but keep something sane
                current_el_symb = current_el_symb or ""

        # If Z is blank, we are continuing isotopes for the same element
        if current is None or current_z is None:
            continue  # shouldn't happen, but be defensive

        a = int(a_s)
        amass = float(amass_s)
        abund = float(abund_s) if abund_s else 0.0

        # Isotope symbol rules:
        # - If symbol given (e.g. "D", "T", or repeats "He"), use it
        # - If blank, inherit the element base symbol (e.g. blank under H -> "H")
        iso_symb = symb_s if symb_s else current_el_symb

        current[a] = (iso_symb, amass, abund)
        count += 1

        # Commit final element into its Z slot
        if current is not None and current_z is not None:
            while len(eldb) <= current_z:
                eldb.append({})
            eldb[current_z] = current

    return eldb, count


def make_files(eldb, n, basename: str):
    fname_h = f"{basename}.h"
    fname_c = f"{basename}.c"

    stamp_lines = [
        "/*",
        " * Isotope database for OpenShieldHIT",
        f' * Autogenerated by "{sys.argv[0]}"',
        f" * {datetime.now().isoformat(' ')}",
        f" * on host {socket.getfqdn()} by user {getpass.getuser()}.",
        " *",
        " * Please do not edit this file.",
        " */",
        "",
    ]
    stamp = "\n".join(stamp_lines) + "\n"

    guard = f"{basename.upper()}_H"

    h_lines = []
    h_lines.append(stamp)
    h_lines.append(f"#ifndef {guard}\n#define {guard}\n")
    h_lines.append("\nstruct isotope {\n")
    h_lines.append("  double amass;   /* atomic mass in amu */\n")
    h_lines.append("  double abund;   /* relative abundance by number */\n")
    h_lines.append("  unsigned int z; /* particle charge */\n")
    h_lines.append("  unsigned int a; /* nucleon number */\n")
    h_lines.append("  char symb[4];   /* chemical symbol */\n")
    h_lines.append("};\n\n")

    nelem = len(eldb)

    h_lines.append(f"#define OSH_ISOTOPE_DB_NISO {n:d}  /* number of isotopes in database */\n")
    h_lines.append(f"#define OSH_ISOTOPE_DB_NELEM {nelem:d}  /* number of elements in database */\n")
    h_lines.append(f"#define OSH_ISOTOPE_DB_ERR 0x{OSH_ISOTOPE_DB_ERR:04X} /* error code */\n\n")
    h_lines.append("extern const struct isotope osh_isotope_db[];\n")
    h_lines.append("extern const unsigned int osh_isotopes_len[];\n")
    h_lines.append("extern const unsigned int osh_isotopes_idx[];\n")
    h_lines.append("extern const unsigned int osh_isotopes_idx_default[];\n")
    h_lines.append(f"#endif /* !{guard} */\n")

    c_lines = []
    c_lines.append(stamp)
    c_lines.append(f'#include "{fname_h}"\n\n')
    c_lines.append("const struct isotope osh_isotope_db[] = {\n")
    c_lines.append("/* relative atomic mass [u], relative abundance, z, A, IUPAC symbol */\n")

    niso = [0] * nelem
    el_idx = [0] * nelem
    el_idx_default = [0] * nelem

    count = 0
    for z, element in enumerate(eldb):
        _niso = len(element)
        niso[z] = _niso
        el_idx[z] = count

        if _niso == 0:
            el_idx_default[z] = OSH_ISOTOPE_DB_ERR
            continue

        best_abund = -1.0
        el_idx_default[z] = count  # fallback to first isotope if all abund are 0

        for a, (symb, amass, abund) in sorted(element.items()):
            if abund > best_abund:
                best_abund = abund
                el_idx_default[z] = count

            line = f'  {{{amass:16.12f}, {abund:.12f}, {z:3d}, {a:3d}, "{symb}"}}'
            if count < n - 1:
                line += ","
            c_lines.append(line + "\n")
            count += 1

    c_lines.append("};\n\n")

    _max_line_length = 110

    # create table with number of isotopes
    line = "  "
    c_lines.append("const unsigned int osh_isotopes_len[] = {\n")
    for i, el in enumerate(eldb):
        if len(line) >= _max_line_length:
            c_lines.append(line + "\n")
            line = "  "

        line += " {:2d}".format(niso[i])
        if i < nelem - 1:
            line += ","
    c_lines.append(line)
    c_lines.append("\n};\n\n")

    # create table with index start array
    line = "  "
    c_lines.append("const unsigned int osh_isotopes_idx[] = {\n")
    for i, el in enumerate(eldb):
        if len(line) >= _max_line_length:
            c_lines.append(line + "\n")
            line = "  "
        line += " {:4d}".format(el_idx[i])
        if i < nelem - 1:
            line += ","
    c_lines.append(line)
    c_lines.append("\n};\n\n")

    # create table with index start array
    line = "  "
    c_lines.append("const unsigned int osh_isotopes_idx_default[] = {\n")
    for i, el in enumerate(eldb):
        if len(line) >= _max_line_length:
            c_lines.append(line + "\n")  # + "/* {:s} */".format(el.value[0]),
            line = "  "
        line += " {:4d}".format(el_idx_default[i])
        if i < nelem - 1:
            line += ","
    c_lines.append(line)
    c_lines.append("\n};\n\n")

    with open(fname_h, "w", encoding="utf-8") as f:
        f.write("".join(h_lines))

    with open(fname_c, "w", encoding="utf-8") as f:
        f.write("".join(c_lines))


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    eldb, n = init_db()
    make_files(eldb, n, BASENAME)
    return 0


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    raise SystemExit(main())
