/* GENERATED by tools/vavilov_fit/emit_landau.py — DO NOT EDIT.
 * Reproducible 1-D fit of the universal (DENLAN) Landau inverse CDF,
 * regenerated from the distribution by the tools/vavilov_fit scripts.
 * Based on an approach by Bjarne Thomsen, Dept. of Physics and Astronomy,
 * Aarhus University, Aarhus, Denmark (2012).  The coefficients are
 * OpenShieldHIT-specific, regenerated from the distribution by these scripts.
 * Worst |lambda_fit - lambda_ref|: 9.65e-03. */
#ifndef OSH_PHYSICS_STRAGGLING_LANDAU_COEFFS_H
#define OSH_PHYSICS_STRAGGLING_LANDAU_COEFFS_H

#define OSH_LAN_NB 4
#define OSH_LAN_MAXP 7
#define OSH_LAN_UMIN 1.0000000000e-03
#define OSH_LAN_UMAX 0.995000

static double const osh_lan_uhi[] = {+5.0000000000e-02, +6.0000000000e-01, +9.5000000000e-01, +9.9510000000e-01};
static int const osh_lan_kind[] = {0, 1, 2, 2};
static int const osh_lan_deg[] = {5, 5, 5, 6};
static double const osh_lan_xmid[] = {+4.9517437763e+00, +3.2500000000e-01, +1.9560115027e+00, +4.1571261737e+00};
static double const osh_lan_xhalf[] = {+1.9560115027e+00, +2.7500000000e-01, +1.0397207708e+00, +1.1613939002e+00};
static double const osh_lan_coef[28] = {
    -2.2016389636e+00, -5.2328354677e-01, +1.2296286022e-01, -3.5797409164e-02, +1.4807859295e-02, -6.4462252788e-03,
    +0.0000000000e+00, +2.1473316907e-01, +1.5831540192e+00, +2.1176174223e-01, +1.6867268243e-01, -4.7870462183e-02,
    +1.1539428917e-01, +0.0000000000e+00, +8.2924387573e+00, +8.6708908676e+00, +3.7040402570e+00, +1.3537825651e+00,
    +3.4959048036e-01, +7.8491772696e-02, +0.0000000000e+00, +6.7581815249e+01, +7.5408684080e+01, +4.3058181959e+01,
    +1.6662798891e+01, +4.8487045420e+00, +1.1842510867e+00, +2.1804218192e-01,
};

#endif /* OSH_PHYSICS_STRAGGLING_LANDAU_COEFFS_H */
